### PR TITLE
Compiled index.js to support deploy_wait_time parameter

### PR DESCRIPTION
**Pull request by legetz**
@tiagonnascimento : Here is another PR to patch compiled JS. All good now?

### CODE REVIEW

**Comment by tiagonnascimento** [comment]
@legetz , done. I just updated the 2.1 to use this version now.

**Comment by tiagonnascimento** [comment]
Thank you for your contribution.

**Comment by legetz** [comment]
@tiagonnascimento : Something went wrong with compilation step. sfdx-orgdev-build-deploy@v2.1 gives me now 
`internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/tiagonnascimento/sfdx-orgdev-build-deploy/v2.1/dist/index.js`

Pipeline has been broken one month since I flipped to another project on january. 
Could you release v2.2 from your current master branch?

**Comment by tiagonnascimento** [comment]
@legetz , could you please try again on 2.1? I just recompile it and made it use the last stable client instead of an old version. I tried and seems to be working now.

**Pull request merged**
